### ISSUE TITLE
No keyboard to key in address

### ISSUE THREAD

**Issue by hyhjcjy** [ocrespo/VNCpp#1]
There is no keyboard to key in address when running this app on cell phone.
Any solution?

**Comment by ocrespo** [comment]
I don't understand you. When you open the app and go to create new connection. If the keyboard doesn't auto-open, you have to click in any field and it will open

**Comment by hyhjcjy** [comment]
No, it didn't open. Neither on the android virtual device nor on my HTC phone.
I don't have another phone to try, maybe it's case dependent?
http://ppt.cc/OfjG

**Comment by ocrespo** [comment]
It's very rare. I tried app in HTC one V and i didn't have any problem. Can you try download the app from google play?

The link is: https://play.google.com/store/apps/details?id=es.farfuteam.vncpp.controller&hl=es_419
or find it in google play with name: vncpp

**Comment by hyhjcjy** [comment]
The keyboard appeared on the app download from google play.
Thank you for quick reply! :)
